[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.11.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.42"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"
